# Generated by Django 3.1.7 on 2021-04-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='SubscribeUsers',
        ),
    ]
