# Generated by Django 3.1.7 on 2021-04-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20210430_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscribeUsers',
            new_name='SubscribeUser',
        ),
    ]
